### ISSUE TITLE
Request of bom file

### ISSUE THREAD

**Issue by DRCRecoveryData** [Daifresne/DT-MIDI-UNO_Hardware#1]
Hi,

Can you upload schematic and pcb files?

Also where is the link of that sanwa you bought?

**Comment by Daifresne** [comment]
schematic and pcb files are already uploaded in the "pcb" file.
and the link of button : https://m.tb.cn/h.g3X1QiH?tk=0EnqWEbTRlc

**Comment by DRCRecoveryData** [comment]
> schematic and pcb files are already uploaded in the "pcb" file.
> 
> and the link of button : https://m.tb.cn/h.g3X1QiH?tk=0EnqWEbTRlc 

Is missing bom file in excel could you export it for me also schematic in pdf too

**Comment by Daifresne** [comment]
List of materials for motherboard and keyboard, The schematic diagrams in PDF format have been uploaded

**Comment by DRCRecoveryData** [comment]
> List of materials for motherboard and keyboard, The schematic diagrams in PDF format have been uploaded

can you upload image of pcb and inside case?

**Comment by Daifresne** [comment]
sure, what else is needed？

**Comment by DRCRecoveryData** [comment]
> sure, what else is needed？

Do you have plan to make block 6 esp32-s3 version?

**Comment by Daifresne** [comment]
> > 当然，还需要什么？
> 
> 你有计划制作 block 6 esp32-s3 版本吗？

Yeah,But not for now,maybe the next year.Becaus I was a high school studient in China.At present,I don't have enough time on this project.

**Comment by DRCRecoveryData** [comment]
> > > 当然，还需要什么？
> 
> > 
> 
> > 你有计划制作 block 6 esp32-s3 版本吗？
> 
> 
> 
> Yeah,But not for now,maybe the next year.Becaus I was a high school studient in China.At present,I don't have enough time on this project.

I have print case here, can you check on your stl file what is the demension hole size of your 64 button version?

![image](https://github.com/Daifresne/DT-MIDI-UNO_Hardware/assets/85211068/a76a1a80-2031-4abc-904f-03dde243366d)

**Comment by Daifresne** [comment]
> > > > 当然，还需要什么？
> > 
> > 
> > > 
> > 
> > 
> > > 你有计划制作 block 6 esp32-s3 版本吗？
> > 
> > 
> > Yeah,But not for now,maybe the next year.Becaus I was a high school studient in China.At present,I don't have enough time on this project.
> 
> I have print case here, can you check on your stl file what is the demension hole size of your 64 button version?
> 
> ![image](https://private-user-images.githubusercontent.com/85211068/342700560-a76a1a80-2031-4abc-904f-03dde243366d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzY0OTksIm5iZiI6MTcxOTMzNjE5OSwicGF0aCI6Ii84NTIxMTA2OC8zNDI3MDA1NjAtYTc2YTFhODAtMjAzMS00YWJjLTkwNGYtMDNkZGUyNDMzNjZkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTdkNDJhNTE1MTYxYWVlMjQ4YjJmYTViZjdjN2FhZWU1MGM4YTZhM2Q1YmNmMzhmZjA5Mzg4OTI3YzNiMWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._2jRObL41-hMAIJc0I9ymIbnseoxLA0R8oUjgs0Q0N8)

![微信截图_20240626012430](https://github.com/Daifresne/DT-MIDI-UNO_Hardware/assets/96587375/b7c0777a-b175-4e62-8057-b9c6ed6f21a2)
24.34mm

**Comment by DRCRecoveryData** [comment]
> > > > > 当然，还需要什么？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你有计划制作 block 6 esp32-s3 版本吗？
> 
> > > 
> 
> > > 
> 
> > > Yeah,But not for now,maybe the next year.Becaus I was a high school studient in China.At present,I don't have enough time on this project.
> 
> > 
> 
> > I have print case here, can you check on your stl file what is the demension hole size of your 64 button version?
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/85211068/342700560-a76a1a80-2031-4abc-904f-03dde243366d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzY0OTksIm5iZiI6MTcxOTMzNjE5OSwicGF0aCI6Ii84NTIxMTA2OC8zNDI3MDA1NjAtYTc2YTFhODAtMjAzMS00YWJjLTkwNGYtMDNkZGUyNDMzNjZkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTdkNDJhNTE1MTYxYWVlMjQ4YjJmYTViZjdjN2FhZWU1MGM4YTZhM2Q1YmNmMzhmZjA5Mzg4OTI3YzNiMWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._2jRObL41-hMAIJc0I9ymIbnseoxLA0R8oUjgs0Q0N8)
> 
> 
> 
> ![微信截图_20240626012430](https://github.com/Daifresne/DT-MIDI-UNO_Hardware/assets/96587375/b7c0777a-b175-4e62-8057-b9c6ed6f21a2)
> 
> 24.34mm

do you have the top plate sketch file before make shape of it?

**Comment by Daifresne** [comment]
> > > > > > 当然，还需要什么？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 你有计划制作 block 6 esp32-s3 版本吗？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yeah,But not for now,maybe the next year.Becaus I was a high school studient in China.At present,I don't have enough time on this project.
> > 
> > 
> > > 
> > 
> > 
> > > I have print case here, can you check on your stl file what is the demension hole size of your 64 button version?
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://private-user-images.githubusercontent.com/85211068/342700560-a76a1a80-2031-4abc-904f-03dde243366d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzY0OTksIm5iZiI6MTcxOTMzNjE5OSwicGF0aCI6Ii84NTIxMTA2OC8zNDI3MDA1NjAtYTc2YTFhODAtMjAzMS00YWJjLTkwNGYtMDNkZGUyNDMzNjZkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTdkNDJhNTE1MTYxYWVlMjQ4YjJmYTViZjdjN2FhZWU1MGM4YTZhM2Q1YmNmMzhmZjA5Mzg4OTI3YzNiMWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._2jRObL41-hMAIJc0I9ymIbnseoxLA0R8oUjgs0Q0N8)
> > 
> > 
> > ![微信截图_20240626012430](https://private-user-images.githubusercontent.com/96587375/342838699-b7c0777a-b175-4e62-8057-b9c6ed6f21a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTA5NzcsIm5iZiI6MTcxOTU5MDY3NywicGF0aCI6Ii85NjU4NzM3NS8zNDI4Mzg2OTktYjdjMDc3N2EtYjE3NS00ZTYyLTgwNTctYjljNmVkNmYyMWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE2MDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMmQ5NDExZjA0MGIzMWE4NWEzNTQ4ODM0NzQ5MTJmMjczM2MyYzYwNzNlNWI1YjNlOGQxNTQyMjA1MGYxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bz05gM5Q2-vQDSmfCAMU6irJvOPk-D79E8EPCMDmVN4)
> > 24.34mm
> 
> do you have the top plate sketch file before make shape of it?

No, I didn't
